### ISSUE TITLE
Incorrect OLEDB source output column data type

### ISSUE THREAD

**Issue by dave-pendleton** [aleonard763/SSIS-Catalog-Archive#1]
The OLEDB source output column, parameter_value in:

3-internal execution_parameter_values\Package\DFT internal_execution_parameter_values

is defined as DT_WSTR (255), it should be DT_NTEXT.

**Comment by aleonard763** [comment]
20211237 - Andy Leonard - looking at this now. Thanks for reporting it!

**Comment by aleonard763** [comment]
Fixed.
